version: '3.8'

services:
  #контейнеры frontend'a
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - 83:80
    environment:
      - VIRTUAL_HOST=api.mangaspace.ru
    volumes:
      - ./configs/nginx.conf/:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    networks:
      - backend

  nodejs:
    container_name: nodejs
    environment:
      - PORT=5174
    build:
      context: dockerfiles
      dockerfile: nodejs.Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ./src:/var/www/laravel
    networks:
      - backend
      
  php:
    container_name: php
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - backend
      - shared

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
      - shared

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:5.2
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_PORT: 3306
    networks:
      - backend
      - shared

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: "--requirepass laravel --user laravel on >laravel ~* allcommands --user default off nopass nocommands"
    ports:
      - 6379:6379
      - 8002:8001
    networks:
      - backend
      - shared

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management-alpine
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "5672:5672"
      # - "15672:15672"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - backend

  supervisor:
    build:
      context: dockerfiles
      dockerfile: supervisor.Dockerfile
    container_name: supervisor
    environment:
      - PORT=8000
    volumes:
      - ./src:/var/www/laravel
      - ./configs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./src/storage/logs:/etc/supervisor/logs
    command: "supervisord -n -c /etc/supervisord.conf"
    ports:
      - 8000:8000
    networks:
      - backend

  # вспомогательные контейнеры
  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - backend

  artisan:
    container_name: artisan
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
    networks:
      - backend

networks:
  backend:
    driver: bridge
  shared:
    driver: bridge
    external: true
